import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import App from "./_app";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <App>{children}</App>
      </body>
    </html>
  );
}
